// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUTAUiTHLajII1NbHm_AoGB9GGheHYv8c',
    appId: '1:852032144647:web:0b2025159a715c7fa9b1a2',
    messagingSenderId: '852032144647',
    projectId: 'fir-auth-cfbe5',
    authDomain: 'fir-auth-cfbe5.firebaseapp.com',
    storageBucket: 'fir-auth-cfbe5.appspot.com',
    measurementId: 'G-DF3GZ1K7G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhUBO29ld3WjTK-OKIUCz5O2KptdNkht8',
    appId: '1:852032144647:android:e79c0c6bd930237fa9b1a2',
    messagingSenderId: '852032144647',
    projectId: 'fir-auth-cfbe5',
    storageBucket: 'fir-auth-cfbe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMw3FHkLVLD5tjf8sHGvPKYZwtld9P0UM',
    appId: '1:852032144647:ios:e134b43e94780873a9b1a2',
    messagingSenderId: '852032144647',
    projectId: 'fir-auth-cfbe5',
    storageBucket: 'fir-auth-cfbe5.appspot.com',
    iosClientId: '852032144647-jrdagc7tp5k07a7mr42p3gv8tbmfolu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
